// Generated by scripts/generate_typescript_client.py from docs/api/v1-openapi.json.
// Do not edit this file by hand; run `python3 scripts/generate_typescript_client.py`.
// SQL compatibility is not implemented.
// Internal TraceDB-only runs are development evidence; exported performance claims require an external control and a number to beat.
// This is a generated transport artifact, not a published managed SDK package.
// Idempotency-Key is caller supplied and local in-process only on current mutation/admin routes.
// It is not durable across restart/crash, not cross-replica, and not exactly-once managed-cloud semantics.

export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonObject | JsonValue[];
export interface JsonObject {
  [key: string]: JsonValue;
}

type TraceDbMethod = "GET" | "POST";

export interface TraceDbFetchResponse {
  ok: boolean;
  status: number;
  text(): Promise<string>;
}

export interface TraceDbFetchInit {
  method: TraceDbMethod;
  headers: Record<string, string>;
  body?: string;
  signal?: unknown;
}

export type TraceDbFetch = (input: string, init: TraceDbFetchInit) => Promise<TraceDbFetchResponse>;

export type TraceDbRequestOptions = {
  headers?: Record<string, string>;
  idempotencyKey?: string;
  signal?: unknown;
};

export type TraceDbClientConfig = {
  baseUrl: string;
  token?: string;
  databaseId?: string;
  branchId?: string;
  fetchImpl?: TraceDbFetch;
};

export class TraceDbHttpError extends Error {
  readonly method: TraceDbMethod;
  readonly path: string;
  readonly status: number;
  readonly body: string;

  constructor(method: TraceDbMethod, path: string, status: number, body: string) {
    super(`TraceDB ${method} ${path} failed with HTTP ${status}: ${body}`);
    this.name = "TraceDbHttpError";
    this.method = method;
    this.path = path;
    this.status = status;
    this.body = body;
  }
}

export class TraceDbClient {
  private readonly baseUrl: string;
  private readonly token?: string;
  private readonly databaseId?: string;
  private readonly branchId?: string;
  private readonly fetchImpl: TraceDbFetch;

  constructor(config: TraceDbClientConfig) {
    const baseUrl = config.baseUrl.replace(/\/+$/, "");
    if (baseUrl.length === 0) {
      throw new Error("TraceDbClientConfig.baseUrl is required");
    }

    const defaultFetch = (globalThis as typeof globalThis & { fetch?: TraceDbFetch }).fetch;
    if (!config.fetchImpl && typeof defaultFetch !== "function") {
      throw new Error("TraceDbClient requires config.fetchImpl when global fetch is unavailable");
    }

    this.baseUrl = baseUrl;
    this.token = config.token;
    this.databaseId = config.databaseId;
    this.branchId = config.branchId;
    this.fetchImpl = config.fetchImpl ?? defaultFetch!;
  }

  // getHealth: GET /v1/health
  /** Health check. */
  async health(options: TraceDbRequestOptions = {}): Promise<JsonValue> {
    return this.request("GET", "/v1/health", undefined, options);
  }

  // getReady: GET /v1/ready
  /** Readiness check. */
  async ready(options: TraceDbRequestOptions = {}): Promise<JsonValue> {
    return this.request("GET", "/v1/ready", undefined, options);
  }

  // getDatabases: GET /v1/databases
  /** List databases. */
  async listDatabases(options: TraceDbRequestOptions = {}): Promise<JsonValue> {
    return this.request("GET", "/v1/databases", undefined, options);
  }

  // getBranches: GET /v1/branches
  /** List branches. */
  async listBranches(options: TraceDbRequestOptions = {}): Promise<JsonValue> {
    return this.request("GET", "/v1/branches", undefined, options);
  }

  // getMetricsPublicSafe: GET /v1/metrics/public-safe
  /** Read public-safe metrics. */
  async publicSafeMetrics(options: TraceDbRequestOptions = {}): Promise<JsonValue> {
    return this.request("GET", "/v1/metrics/public-safe", undefined, options);
  }

  // postSchemaApply: POST /v1/schema/apply
  /** Apply table schema. Mutates TraceDB state. Caller may provide Idempotency-Key. */
  async applySchema(body: JsonObject, options: TraceDbRequestOptions = {}): Promise<JsonValue> {
    return this.request("POST", "/v1/schema/apply", body, options);
  }

  // postInsert: POST /v1/insert
  /** Insert record compatibility route. Mutates TraceDB state. Caller may provide Idempotency-Key. */
  async insert(body: JsonObject, options: TraceDbRequestOptions = {}): Promise<JsonValue> {
    return this.request("POST", "/v1/insert", body, options);
  }

  // postRecordsPut: POST /v1/records/put
  /** Put record. Mutates TraceDB state. Caller may provide Idempotency-Key. */
  async putRecord(body: JsonObject, options: TraceDbRequestOptions = {}): Promise<JsonValue> {
    return this.request("POST", "/v1/records/put", body, options);
  }

  // postRecordsPutBatch: POST /v1/records/put-batch
  /** Put record batch. Mutates TraceDB state. Caller may provide Idempotency-Key. */
  async putBatch(body: JsonObject, options: TraceDbRequestOptions = {}): Promise<JsonValue> {
    return this.request("POST", "/v1/records/put-batch", body, options);
  }

  // postRecordsPatch: POST /v1/records/patch
  /** Patch record. Mutates TraceDB state. Caller may provide Idempotency-Key. */
  async patchRecord(body: JsonObject, options: TraceDbRequestOptions = {}): Promise<JsonValue> {
    return this.request("POST", "/v1/records/patch", body, options);
  }

  // postRecordsDelete: POST /v1/records/delete
  /** Delete record. Mutates TraceDB state. Caller may provide Idempotency-Key. */
  async deleteRecord(body: JsonObject, options: TraceDbRequestOptions = {}): Promise<JsonValue> {
    return this.request("POST", "/v1/records/delete", body, options);
  }

  // postRecordsGet: POST /v1/records/get
  /** Get record. */
  async getRecord(body: JsonObject, options: TraceDbRequestOptions = {}): Promise<JsonValue> {
    return this.request("POST", "/v1/records/get", body, options);
  }

  // postRecordsScan: POST /v1/records/scan
  /** Scan records. */
  async scanRecords(body: JsonObject, options: TraceDbRequestOptions = {}): Promise<JsonValue> {
    return this.request("POST", "/v1/records/scan", body, options);
  }

  // postQuery: POST /v1/query
  /** Run hybrid query. */
  async query(body: JsonObject, options: TraceDbRequestOptions = {}): Promise<JsonValue> {
    return this.request("POST", "/v1/query", body, options);
  }

  // postExplain: POST /v1/explain
  /** Explain hybrid query. */
  async explain(body: JsonObject, options: TraceDbRequestOptions = {}): Promise<JsonValue> {
    return this.request("POST", "/v1/explain", body, options);
  }

  // postAdminCompact: POST /v1/admin/compact
  /** Compact local engine state. Mutates TraceDB state. Caller may provide Idempotency-Key. */
  async compact(body: JsonObject = {}, options: TraceDbRequestOptions = {}): Promise<JsonValue> {
    return this.request("POST", "/v1/admin/compact", body, options);
  }

  // postAdminSnapshot: POST /v1/admin/snapshot
  /** Create snapshot. Mutates TraceDB state. Caller may provide Idempotency-Key. */
  async snapshot(body: JsonObject, options: TraceDbRequestOptions = {}): Promise<JsonValue> {
    return this.request("POST", "/v1/admin/snapshot", body, options);
  }

  // postAdminRestore: POST /v1/admin/restore
  /** Restore snapshot. Mutates TraceDB state. Caller may provide Idempotency-Key. */
  async restore(body: JsonObject, options: TraceDbRequestOptions = {}): Promise<JsonValue> {
    return this.request("POST", "/v1/admin/restore", body, options);
  }

  // getAdminJobs: GET /v1/admin/jobs
  /** List admin jobs. */
  async listAdminJobs(options: TraceDbRequestOptions = {}): Promise<JsonValue> {
    return this.request("GET", "/v1/admin/jobs", undefined, options);
  }

  private async request(
    method: TraceDbMethod,
    path: string,
    body: JsonObject | undefined,
    options: TraceDbRequestOptions,
  ): Promise<JsonValue> {
    const headers: Record<string, string> = {
      Accept: "application/json",
      ...options.headers,
    };

    if (this.token) {
      headers.Authorization = `Bearer ${this.token}`;
    }
    if (method !== "GET") {
      headers["Content-Type"] = headers["Content-Type"] ?? "application/json";
    }
    if (options.idempotencyKey) {
      headers["Idempotency-Key"] = options.idempotencyKey;
    }

    const init: TraceDbFetchInit = { method, headers };
    if (options.signal !== undefined) {
      init.signal = options.signal;
    }
    if (method !== "GET") {
      init.body = JSON.stringify(this.withRoutingMetadata(body ?? {}));
    }

    const response = await this.fetchImpl(`${this.baseUrl}${path}`, init);
    const responseBody = await response.text();
    if (!response.ok) {
      throw new TraceDbHttpError(method, path, response.status, responseBody);
    }

    const trimmed = responseBody.trim();
    if (trimmed.length === 0) {
      return null;
    }
    return JSON.parse(trimmed) as JsonValue;
  }

  private withRoutingMetadata(body: JsonObject): JsonObject {
    if (!this.databaseId && !this.branchId) {
      return body;
    }

    const routed: JsonObject = { ...body };
    if (this.databaseId && routed.database_id === undefined) {
      routed.database_id = this.databaseId;
    }
    if (this.branchId && routed.branch_id === undefined) {
      routed.branch_id = this.branchId;
    }
    return routed;
  }
}
