// Generated by scripts/generate_typescript_client.py from docs/api/v1-openapi.json.
// Do not edit this file by hand; run `python3 scripts/generate_typescript_client.py`.
// SQL compatibility is not implemented.
// Internal TraceDB-only runs are development evidence; exported performance claims require an external control and a number to beat.
// This is a generated transport artifact, not a published managed SDK package.
// Idempotency-Key is caller supplied and local in-process only on current mutation/admin routes.
// It is not durable across restart/crash, not cross-replica, and not exactly-once managed-cloud semantics.

export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonObject | JsonValue[];
export interface JsonObject {
  [key: string]: JsonValue | undefined;
}

type TraceDbMethod = "GET" | "POST";

export interface TraceDbFetchResponse {
  ok: boolean;
  status: number;
  text(): Promise<string>;
}

export interface TraceDbFetchInit {
  method: TraceDbMethod;
  headers: Record<string, string>;
  body?: string;
  signal?: unknown;
}

export type TraceDbFetch = (input: string, init: TraceDbFetchInit) => Promise<TraceDbFetchResponse>;

export type TraceDbRequestOptions = {
  headers?: Record<string, string>;
  idempotencyKey?: string;
  signal?: unknown;
};

export type TraceDbClientConfig = {
  baseUrl: string;
  token?: string;
  databaseId?: string;
  branchId?: string;
  fetchImpl?: TraceDbFetch;
};

export class TraceDbHttpError extends Error {
  readonly method: TraceDbMethod;
  readonly path: string;
  readonly status: number;
  readonly body: string;

  constructor(method: TraceDbMethod, path: string, status: number, body: string) {
    super(`TraceDB ${method} ${path} failed with HTTP ${status}: ${body}`);
    this.name = "TraceDbHttpError";
    this.method = method;
    this.path = path;
    this.status = status;
    this.body = body;
  }
}

export class TraceDbRequestError extends Error {
  readonly method: TraceDbMethod;
  readonly path: string;

  constructor(method: TraceDbMethod, path: string, message: string) {
    super(`TraceDB ${method} ${path} request invalid: ${message}`);
    this.name = "TraceDbRequestError";
    this.method = method;
    this.path = path;
  }
}

// Generated schema aliases keep OpenAPI's permissive additionalProperties boundary.
// Known fields are optional; runtime validation remains server-side.

export interface AccessPathExplain extends JsonObject {
  access_path_id?: string;
  candidates?: number;
  opened?: boolean;
  visibility_checked_before_open?: boolean;
}

export interface AccessPathTiming extends JsonObject {
  access_path_id?: string;
  build_ms?: number;
  open_ms?: number;
}

export interface BranchesResponse extends JsonObject {
}

export interface Candidate extends JsonObject {
  freshness?: string;
  record_id?: string;
  score_components?: HybridScoreComponents;
  score_upper_bound?: number | null;
  source?: string;
  version_id?: number;
  visibility_checked?: boolean;
}

export interface CompactResponse extends JsonObject {
  compacted?: boolean;
}

export interface DatabasesResponse extends JsonObject {
}

export interface DeleteResponse extends JsonObject {
  deleted?: boolean;
  epoch?: number;
}

export interface EmptyObject extends JsonObject {
}

export interface EpochResponse extends JsonObject {
  epoch?: number;
}

export interface ErrorResponse extends JsonObject {
  error?: string;
}

export interface GetRecordResponse extends JsonObject {
  record?: RecordOutput | null;
}

export interface HealthResponse extends JsonObject {
}

export interface HybridExplain extends JsonObject {
  access_path_timings?: AccessPathTiming[];
  access_paths?: AccessPathExplain[];
  candidate_budget?: number;
  deduped_candidate_count?: number;
  dirty_feature_count?: number;
  early_stop_reason?: string | null;
  exact_fallback_triggered?: boolean;
  failed_feature_count?: number;
  final_visibility_guard_count?: number;
  final_visibility_guard_removed?: number;
  freshness_mode?: string;
  fusion_method?: string;
  hot_overlay_searched?: boolean;
  lexical_cache_hits?: number;
  lexical_cache_misses?: number;
  lexical_indexed_documents?: number;
  lexical_scored_documents?: number;
  materialized_count?: number;
  missing_feature_count?: number;
  module_versions?: string[];
  opened_candidate_streams?: string[];
  pending_feature_count?: number;
  phase_timings?: QueryPhaseTiming[];
  planner_candidates?: Candidate[];
  policy_epoch?: number;
  read_epoch?: number;
  returned_count?: number;
  scalar_filter_applied?: boolean;
  scalar_filter_predicates?: string[];
  scalar_filter_removed_records?: number;
  scalar_filter_visible_records?: number;
  schema_epoch?: number;
  segments_scanned?: number;
  selected_strategy?: string | null;
  skipped_access_paths?: string[];
  tenant_mask_visible_records?: number;
  text_candidates?: number;
  vector_candidates?: number;
}

export interface HybridQuery extends JsonObject {
  explain?: boolean;
  freshness?: string;
  graph_seed?: string | null;
  scalar_eq?: JsonObject;
  table?: string;
  temporal_as_of?: number | null;
  tenant_id?: string;
  text?: string | null;
  top_k?: number;
  vector?: number[] | null;
}

export interface HybridQueryRow extends JsonObject {
  fields?: JsonObject;
  record_id?: string;
  score?: HybridScoreComponents;
  tenant_id?: string;
  version_id?: number;
}

export interface HybridScoreComponents extends JsonObject {
  final_score?: number;
  freshness_penalty?: number | null;
  lexical?: number | null;
  relational?: number | null;
  vector?: number | null;
}

export interface JobsResponse extends JsonObject {
}

export interface MetricsResponse extends JsonObject {
}

export interface PutBatchResponse extends JsonObject {
  epoch?: number;
  record_count?: number;
  write_timing?: JsonObject;
}

export interface QueryPhaseTiming extends JsonObject {
  elapsed_ms?: number;
  phase?: string;
}

export interface QueryResponse extends JsonObject {
  explain?: HybridExplain;
  results?: HybridQueryRow[];
}

export interface ReadyResponse extends JsonObject {
}

export interface RecordDeleteRequest extends JsonObject {
  id?: string;
  table?: string;
  tenant_id?: string;
  tombstone?: string;
}

export interface RecordGetRequest extends JsonObject {
  id?: string;
  table?: string;
  tenant_id?: string;
}

export interface RecordInput extends JsonObject {
  fields?: JsonObject;
  id?: string;
  table?: string;
  tenant_id?: string;
}

export interface RecordOutput extends JsonObject {
  fields?: JsonObject;
  id?: string;
  table?: string;
  tenant_id?: string;
  version_id?: number;
}

export interface RecordPatchRequest extends JsonObject {
  fields?: JsonObject;
  id?: string;
  table?: string;
  tenant_id?: string;
}

export interface RecordPutBatchRequest extends JsonObject {
  include_write_timing?: boolean;
  records?: RecordInput[];
}

export type RecordPutBody = RecordInput | RecordPutRequest;

export interface RecordPutRequest extends JsonObject {
  record?: RecordInput;
}

export interface RecordScanOutput extends JsonObject {
  records?: RecordOutput[];
  returned_count?: number;
}

export interface RecordScanRequest extends JsonObject {
  limit?: number;
  table?: string;
  tenant_id?: string;
}

export interface RestoreRequest extends JsonObject {
  source?: string;
  target?: string;
}

export interface RestoreResponse extends JsonObject {
  restored?: boolean;
  source?: string;
  target?: string;
}

export interface SnapshotRequest extends JsonObject {
  target?: string;
}

export interface SnapshotResponse extends JsonObject {
  snapshot?: boolean;
  target?: string;
}

export interface TableSchema extends JsonObject {
  name?: string;
  primary_id_column?: string;
  scalar_columns?: string[];
  tenant_id_column?: string;
  text_indexed_columns?: string[];
  vector_columns?: JsonObject[];
}
export class TraceDbClient {
  private readonly baseUrl: string;
  private readonly token?: string;
  private readonly databaseId?: string;
  private readonly branchId?: string;
  private readonly fetchImpl: TraceDbFetch;

  constructor(config: TraceDbClientConfig) {
    const baseUrl = config.baseUrl.replace(/\/+$/, "");
    if (baseUrl.length === 0) {
      throw new Error("TraceDbClientConfig.baseUrl is required");
    }

    const defaultFetch = (globalThis as typeof globalThis & { fetch?: TraceDbFetch }).fetch;
    if (!config.fetchImpl && typeof defaultFetch !== "function") {
      throw new Error("TraceDbClient requires config.fetchImpl when global fetch is unavailable");
    }

    this.baseUrl = baseUrl;
    this.token = config.token;
    this.databaseId = config.databaseId;
    this.branchId = config.branchId;
    this.fetchImpl = config.fetchImpl ?? defaultFetch!;
  }

  // getHealth: GET /v1/health
  /** Health check. */
  async health(options: TraceDbRequestOptions = {}): Promise<HealthResponse> {
    return this.request<HealthResponse>("GET", "/v1/health", undefined, options);
  }

  // getReady: GET /v1/ready
  /** Readiness check. */
  async ready(options: TraceDbRequestOptions = {}): Promise<ReadyResponse> {
    return this.request<ReadyResponse>("GET", "/v1/ready", undefined, options);
  }

  // getDatabases: GET /v1/databases
  /** List databases. */
  async listDatabases(options: TraceDbRequestOptions = {}): Promise<DatabasesResponse> {
    return this.request<DatabasesResponse>("GET", "/v1/databases", undefined, options);
  }

  // getBranches: GET /v1/branches
  /** List branches. */
  async listBranches(options: TraceDbRequestOptions = {}): Promise<BranchesResponse> {
    return this.request<BranchesResponse>("GET", "/v1/branches", undefined, options);
  }

  // getMetricsPublicSafe: GET /v1/metrics/public-safe
  /** Read public-safe metrics. */
  async publicSafeMetrics(options: TraceDbRequestOptions = {}): Promise<MetricsResponse> {
    return this.request<MetricsResponse>("GET", "/v1/metrics/public-safe", undefined, options);
  }

  // postSchemaApply: POST /v1/schema/apply
  /** Apply table schema. Mutates TraceDB state. Caller may provide Idempotency-Key. */
  async applySchema(body: TableSchema, options: TraceDbRequestOptions = {}): Promise<EpochResponse> {
    return this.request<EpochResponse>("POST", "/v1/schema/apply", body, options);
  }

  // postInsert: POST /v1/insert
  /** Insert record compatibility route. Mutates TraceDB state. Caller may provide Idempotency-Key. */
  async insert(body: RecordInput, options: TraceDbRequestOptions = {}): Promise<EpochResponse> {
    return this.request<EpochResponse>("POST", "/v1/insert", body, options);
  }

  // postRecordsPut: POST /v1/records/put
  /** Put record. Mutates TraceDB state. Caller may provide Idempotency-Key. */
  async putRecord(body: RecordPutBody, options: TraceDbRequestOptions = {}): Promise<EpochResponse> {
    return this.request<EpochResponse>("POST", "/v1/records/put", body, options);
  }

  // postRecordsPutBatch: POST /v1/records/put-batch
  /** Put record batch. Mutates TraceDB state. Caller may provide Idempotency-Key. */
  async putBatch(body: RecordPutBatchRequest, options: TraceDbRequestOptions = {}): Promise<PutBatchResponse> {
    return this.request<PutBatchResponse>("POST", "/v1/records/put-batch", body, options);
  }

  // postRecordsPatch: POST /v1/records/patch
  /** Patch record. Mutates TraceDB state. Caller may provide Idempotency-Key. */
  async patchRecord(body: RecordPatchRequest, options: TraceDbRequestOptions = {}): Promise<EpochResponse> {
    return this.request<EpochResponse>("POST", "/v1/records/patch", body, options);
  }

  // postRecordsDelete: POST /v1/records/delete
  /** Delete record. Mutates TraceDB state. Caller may provide Idempotency-Key. */
  async deleteRecord(body: RecordDeleteRequest, options: TraceDbRequestOptions = {}): Promise<DeleteResponse> {
    return this.request<DeleteResponse>("POST", "/v1/records/delete", body, options);
  }

  // postRecordsGet: POST /v1/records/get
  /** Get record. */
  async getRecord(body: RecordGetRequest, options: TraceDbRequestOptions = {}): Promise<GetRecordResponse> {
    return this.request<GetRecordResponse>("POST", "/v1/records/get", body, options);
  }

  // postRecordsScan: POST /v1/records/scan
  /** Scan records. */
  async scanRecords(body: RecordScanRequest, options: TraceDbRequestOptions = {}): Promise<RecordScanOutput> {
    return this.request<RecordScanOutput>("POST", "/v1/records/scan", body, options);
  }

  // postQuery: POST /v1/query
  /** Run hybrid query. */
  async query(body: HybridQuery, options: TraceDbRequestOptions = {}): Promise<QueryResponse> {
    return this.request<QueryResponse>("POST", "/v1/query", body, options);
  }

  // postExplain: POST /v1/explain
  /** Explain hybrid query. */
  async explain(body: HybridQuery, options: TraceDbRequestOptions = {}): Promise<HybridExplain> {
    return this.request<HybridExplain>("POST", "/v1/explain", body, options);
  }

  // postAdminCompact: POST /v1/admin/compact
  /** Compact local engine state. Mutates TraceDB state. Caller may provide Idempotency-Key. */
  async compact(body: EmptyObject = {}, options: TraceDbRequestOptions = {}): Promise<CompactResponse> {
    return this.request<CompactResponse>("POST", "/v1/admin/compact", body, options);
  }

  // postAdminSnapshot: POST /v1/admin/snapshot
  /** Create snapshot. Mutates TraceDB state. Caller may provide Idempotency-Key. */
  async snapshot(body: SnapshotRequest, options: TraceDbRequestOptions = {}): Promise<SnapshotResponse> {
    return this.request<SnapshotResponse>("POST", "/v1/admin/snapshot", body, options);
  }

  // postAdminRestore: POST /v1/admin/restore
  /** Restore snapshot. Mutates TraceDB state. Caller may provide Idempotency-Key. */
  async restore(body: RestoreRequest, options: TraceDbRequestOptions = {}): Promise<RestoreResponse> {
    return this.request<RestoreResponse>("POST", "/v1/admin/restore", body, options);
  }

  // getAdminJobs: GET /v1/admin/jobs
  /** List admin jobs. */
  async listAdminJobs(options: TraceDbRequestOptions = {}): Promise<JobsResponse> {
    return this.request<JobsResponse>("GET", "/v1/admin/jobs", undefined, options);
  }

  private async request<TResponse extends JsonValue>(
    method: TraceDbMethod,
    path: string,
    body: JsonObject | undefined,
    options: TraceDbRequestOptions,
  ): Promise<TResponse> {
    const headers: Record<string, string> = {
      Accept: "application/json",
      ...options.headers,
    };

    if (this.token) {
      headers.Authorization = `Bearer ${this.token}`;
    }
    if (method !== "GET") {
      headers["Content-Type"] = headers["Content-Type"] ?? "application/json";
    }
    const idempotencyKey = this.validatedIdempotencyKey(method, path, options);
    if (idempotencyKey !== undefined) {
      headers["Idempotency-Key"] = idempotencyKey;
    }

    const init: TraceDbFetchInit = { method, headers };
    if (options.signal !== undefined) {
      init.signal = options.signal;
    }
    if (method !== "GET") {
      init.body = JSON.stringify(this.withRoutingMetadata(body ?? {}));
    }

    const response = await this.fetchImpl(`${this.baseUrl}${path}`, init);
    const responseBody = await response.text();
    if (!response.ok) {
      throw new TraceDbHttpError(method, path, response.status, responseBody);
    }

    const trimmed = responseBody.trim();
    if (trimmed.length === 0) {
      return null as TResponse;
    }
    return JSON.parse(trimmed) as TResponse;
  }

  private withRoutingMetadata(body: JsonObject): JsonObject {
    if (!this.databaseId && !this.branchId) {
      return body;
    }

    const routed: JsonObject = { ...body };
    if (this.databaseId && routed.database_id === undefined) {
      routed.database_id = this.databaseId;
    }
    if (this.branchId && routed.branch_id === undefined) {
      routed.branch_id = this.branchId;
    }
    return routed;
  }

  private validatedIdempotencyKey(
    method: TraceDbMethod,
    path: string,
    options: TraceDbRequestOptions,
  ): string | undefined {
    const key = options.idempotencyKey;
    if (key === undefined) {
      return undefined;
    }
    if (key.length === 0 || key.includes("\r") || key.includes("\n")) {
      throw new TraceDbRequestError(
        method,
        path,
        "idempotency key must be non-empty and must not contain CR or LF",
      );
    }
    return key;
  }
}
