#!/usr/bin/env python3
"""Generate the checked-in TraceDB v1 TypeScript fetch client artifact."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
OPENAPI_ARTIFACT = ROOT / "docs" / "api" / "v1-openapi.json"
CLIENT_ARTIFACT = ROOT / "clients" / "typescript" / "src" / "client.ts"

METHOD_NAME_OVERRIDES = {
    "getHealth": "health",
    "getReady": "ready",
    "getDatabases": "listDatabases",
    "getBranches": "listBranches",
    "getMetricsPublicSafe": "publicSafeMetrics",
    "postSchemaApply": "applySchema",
    "postInsert": "insert",
    "postRecordsPut": "putRecord",
    "postRecordsPutBatch": "putBatch",
    "postRecordsPatch": "patchRecord",
    "postRecordsDelete": "deleteRecord",
    "postRecordsGet": "getRecord",
    "postRecordsScan": "scanRecords",
    "postQuery": "query",
    "postExplain": "explain",
    "postAdminCompact": "compact",
    "postAdminSnapshot": "snapshot",
    "postAdminRestore": "restore",
    "getAdminJobs": "listAdminJobs",
}

OPERATION_ORDER = [
    "getHealth",
    "getReady",
    "getDatabases",
    "getBranches",
    "getMetricsPublicSafe",
    "postSchemaApply",
    "postInsert",
    "postRecordsPut",
    "postRecordsPutBatch",
    "postRecordsPatch",
    "postRecordsDelete",
    "postRecordsGet",
    "postRecordsScan",
    "postQuery",
    "postExplain",
    "postAdminCompact",
    "postAdminSnapshot",
    "postAdminRestore",
    "getAdminJobs",
]


class Operation(dict[str, Any]):
    pass


def load_operations() -> list[Operation]:
    spec = json.loads(OPENAPI_ARTIFACT.read_text())
    operations_by_id: dict[str, Operation] = {}
    paths = spec.get("paths", {})
    for path, methods in paths.items():
        for method, operation in methods.items():
            operation_id = operation["operationId"]
            operations_by_id[operation_id] = Operation(
                operation_id=operation_id,
                method=method.upper(),
                path=path,
                summary=operation.get("summary", ""),
                has_body="requestBody" in operation,
                mutates_state=operation.get("x-tracedb-mutates-state", False),
                safe_retry=operation.get("x-tracedb-sdk-safe-retry", False),
                idempotency_supported=operation.get("x-tracedb-idempotency-key-supported", False),
            )

    missing = [operation_id for operation_id in OPERATION_ORDER if operation_id not in operations_by_id]
    if missing:
        raise SystemExit(f"{OPENAPI_ARTIFACT} is missing expected operationIds: {', '.join(missing)}")

    extra = sorted(set(operations_by_id) - set(OPERATION_ORDER))
    if extra:
        raise SystemExit(f"{OPENAPI_ARTIFACT} has unhandled operationIds: {', '.join(extra)}")

    return [operations_by_id[operation_id] for operation_id in OPERATION_ORDER]


def render_header() -> str:
    return """// Generated by scripts/generate_typescript_client.py from docs/api/v1-openapi.json.
// Do not edit this file by hand; run `python3 scripts/generate_typescript_client.py`.
// SQL compatibility is not implemented.
// Internal TraceDB-only runs are development evidence; exported performance claims require an external control and a number to beat.
// This is a generated transport artifact, not a published managed SDK package.
// Idempotency-Key is caller supplied and local in-process only on current mutation/admin routes.
// It is not durable across restart/crash, not cross-replica, and not exactly-once managed-cloud semantics.

export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonObject | JsonValue[];
export interface JsonObject {
  [key: string]: JsonValue;
}

type TraceDbMethod = "GET" | "POST";

export interface TraceDbFetchResponse {
  ok: boolean;
  status: number;
  text(): Promise<string>;
}

export interface TraceDbFetchInit {
  method: TraceDbMethod;
  headers: Record<string, string>;
  body?: string;
  signal?: unknown;
}

export type TraceDbFetch = (input: string, init: TraceDbFetchInit) => Promise<TraceDbFetchResponse>;

export type TraceDbRequestOptions = {
  headers?: Record<string, string>;
  idempotencyKey?: string;
  signal?: unknown;
};

export type TraceDbClientConfig = {
  baseUrl: string;
  token?: string;
  databaseId?: string;
  branchId?: string;
  fetchImpl?: TraceDbFetch;
};

export class TraceDbHttpError extends Error {
  readonly method: TraceDbMethod;
  readonly path: string;
  readonly status: number;
  readonly body: string;

  constructor(method: TraceDbMethod, path: string, status: number, body: string) {
    super(`TraceDB ${method} ${path} failed with HTTP ${status}: ${body}`);
    this.name = "TraceDbHttpError";
    this.method = method;
    this.path = path;
    this.status = status;
    this.body = body;
  }
}

"""


def render_class_start() -> str:
    return """export class TraceDbClient {
  private readonly baseUrl: string;
  private readonly token?: string;
  private readonly databaseId?: string;
  private readonly branchId?: string;
  private readonly fetchImpl: TraceDbFetch;

  constructor(config: TraceDbClientConfig) {
    const baseUrl = config.baseUrl.replace(/\\/+$/, "");
    if (baseUrl.length === 0) {
      throw new Error("TraceDbClientConfig.baseUrl is required");
    }

    const defaultFetch = (globalThis as typeof globalThis & { fetch?: TraceDbFetch }).fetch;
    if (!config.fetchImpl && typeof defaultFetch !== "function") {
      throw new Error("TraceDbClient requires config.fetchImpl when global fetch is unavailable");
    }

    this.baseUrl = baseUrl;
    this.token = config.token;
    this.databaseId = config.databaseId;
    this.branchId = config.branchId;
    this.fetchImpl = config.fetchImpl ?? defaultFetch!;
  }

"""


def render_operation(operation: Operation) -> str:
    method_name = METHOD_NAME_OVERRIDES[operation["operation_id"]]
    method = operation["method"]
    path = operation["path"]
    operation_id = operation["operation_id"]
    summary = operation["summary"]
    mutates_note = " Mutates TraceDB state." if operation["mutates_state"] else ""
    retry_note = " Caller may provide Idempotency-Key." if operation["idempotency_supported"] else ""

    if operation["has_body"]:
        default_body = " = {}" if operation_id == "postAdminCompact" else ""
        signature = f"body: JsonObject{default_body}, options: TraceDbRequestOptions = {{}}"
        body_arg = "body"
    else:
        signature = "options: TraceDbRequestOptions = {}"
        body_arg = "undefined"

    return f"""  // {operation_id}: {method} {path}
  /** {summary}.{mutates_note}{retry_note} */
  async {method_name}({signature}): Promise<JsonValue> {{
    return this.request("{method}", "{path}", {body_arg}, options);
  }}

"""


def render_helpers() -> str:
    return """  private async request(
    method: TraceDbMethod,
    path: string,
    body: JsonObject | undefined,
    options: TraceDbRequestOptions,
  ): Promise<JsonValue> {
    const headers: Record<string, string> = {
      Accept: "application/json",
      ...options.headers,
    };

    if (this.token) {
      headers.Authorization = `Bearer ${this.token}`;
    }
    if (method !== "GET") {
      headers["Content-Type"] = headers["Content-Type"] ?? "application/json";
    }
    if (options.idempotencyKey) {
      headers["Idempotency-Key"] = options.idempotencyKey;
    }

    const init: TraceDbFetchInit = { method, headers };
    if (options.signal !== undefined) {
      init.signal = options.signal;
    }
    if (method !== "GET") {
      init.body = JSON.stringify(this.withRoutingMetadata(body ?? {}));
    }

    const response = await this.fetchImpl(`${this.baseUrl}${path}`, init);
    const responseBody = await response.text();
    if (!response.ok) {
      throw new TraceDbHttpError(method, path, response.status, responseBody);
    }

    const trimmed = responseBody.trim();
    if (trimmed.length === 0) {
      return null;
    }
    return JSON.parse(trimmed) as JsonValue;
  }

  private withRoutingMetadata(body: JsonObject): JsonObject {
    if (!this.databaseId && !this.branchId) {
      return body;
    }

    const routed: JsonObject = { ...body };
    if (this.databaseId && routed.database_id === undefined) {
      routed.database_id = this.databaseId;
    }
    if (this.branchId && routed.branch_id === undefined) {
      routed.branch_id = this.branchId;
    }
    return routed;
  }
}
"""


def render_client() -> str:
    operations = load_operations()
    methods = "".join(render_operation(operation) for operation in operations)
    return render_header() + render_class_start() + methods + render_helpers()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the checked-in artifact is stale")
    args = parser.parse_args()

    rendered = render_client()
    if args.check:
        current = CLIENT_ARTIFACT.read_text() if CLIENT_ARTIFACT.exists() else ""
        if current != rendered:
            print(f"{CLIENT_ARTIFACT} is stale; run scripts/generate_typescript_client.py", flush=True)
            return 1
        return 0

    CLIENT_ARTIFACT.parent.mkdir(parents=True, exist_ok=True)
    CLIENT_ARTIFACT.write_text(rendered)
    print(CLIENT_ARTIFACT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
